[build]
builder = "dockerfile"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/"
healthcheckTimeout = 60

[[services]]
name = "vk2discord-bot"
port = 8080

[environments]
  [environments.production]
  [environments.development]